[project]
name = "prowess-tracker"
version = "0.1.0"
description = "Magic: The Gathering tracker for prowess, storm, and mana pool"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "kivy>=2.3.1",
]

[tool.uv]
# optional: auto-install dependencies on run
